baseURL = "https://blog.trontria.com/"
languageCode = "en-us"
title = "tròn trịa"
theme = "PaperMod"

[[params.socialIcons]]
name = "Facebook"
url = "https://www.facebook.com/supertrontria"
[[params.socialIcons]]
name = "Instagram"
url = "https://www.instagram.com/supertro_n_"
[[params.socialIcons]]
name = "Github"
url = "https://github.com/nquangtrung"

[params.profileMode]
enabled = true
title = "the adventures of trung tròn trịa"
subtitle = "on dev, life, and everything besides"
imageUrl = "https://res.cloudinary.com/dhqxdkpus/image/upload/w_120,h_120,c_scale/home/top.png"
imageTitle = "would you join me for a quick run?"
imageWidth = 120
imageHeight = 120
[[params.profileMode.buttons]]
url = "/archives"
name = "blog"
