baseURL = "https://blog.trontria.com/"
languageCode = "en-us"
title = "Tròn trịa"
theme = "PaperMod"

[[params.socialIcons]]
name = "Facebook"
url = "https://www.facebook.com/supertrontria"
[[params.socialIcons]]
name = "Instagram"
url = "https://www.instagram.com/supertro_n_"
[[params.socialIcons]]
name = "Github"
url = "https://www.instagram.com/nquangtrung"

[params.profileMode]
enabled = true
title = "TRÒN TRỊA"
subtitle = "on dev, life, and everything besides"
imageUrl = "https://firebasestorage.googleapis.com/v0/b/trontria-blog.appspot.com/o/home%2Ftop.png?alt=media&token=ee2a5a7b-7414-4e84-9b2f-59052696bf39"
imageTitle = "would you run with me?"
imageWidth = 120
imageHeight = 120
[[params.profileMode.buttons]]
url = "/archives"
name = "blog"
